# I/O
datasheet: 'resources/datasets/meta/filtered_datasets_hg38.csv'
output_dir: 'results'

# Pre-processing
qc: true
norm: false
log_norm: false
scale: false
hvg: false
# Merge & Harmonize
zero_padding: true
correction_method: 'skip'
